import Head from "next/head";
import { postCardInfo } from "../types";
import PostCard from "../components/post/PostCard";

export async function getStaticProps() {
  return {
    props: {
      posts: [
        {
          id: "sss",
          href: "sss",
          imageSrc: "https://i.ibb.co/QvHKzBR/schedule.jpg",
          name: "sss",
          username: "sss",
        },
        {
          id: "sss",
          href: "sss",
          imageSrc: "https://i.ibb.co/0FhX2nJ/Use-username-instead-of-email.png",
          name: "sss",
          username: "sss",
        },
        {
          id: "sss",
          href: "sss",
          imageSrc: "https://i.ibb.co/QvHKzBR/schedule.jpg",
          name: "sss",
          username: "sss",
        },
        {
          id: "sss",
          href: "sss",
          imageSrc: "https://i.ibb.co/0FhX2nJ/Use-username-instead-of-email.png",
          name: "sss",
          username: "sss",
        },
        {
          id: "sss",
          href: "sss",
          imageSrc: "https://i.ibb.co/QvHKzBR/schedule.jpg",
          name: "sss",
          username: "sss",
        },
        {
          id: "sss",
          href: "sss",
          imageSrc: "https://i.ibb.co/0FhX2nJ/Use-username-instead-of-email.png",
          name: "sss",
          username: "sss",
        },
      ],
    },
  };
}
export default function Home({ posts }: { posts: postCardInfo[] }) {
  return (
    <>
      <Head>
        <title>Dex</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1 className='text-4xl sm:text-7xl text-center font-Poppins sm:mt-10 mt-8'>Explore</h1>
        <section className='mx-auto max-w-2xl py-8 px-4 sm:py-10 sm:px-6 lg:max-w-7xl lg:px-8 font-Poppins'>
          <div className='grid grid-cols-1 gap-y-10 gap-x-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 xl:gap-x-8'>
            {posts.map((image) => (
              <PostCard key={image.id} image={image} />
            ))}
          </div>
        </section>
      </main>
    </>
  );
}
