import axios from "axios";
import Head from "next/head";
import { toast } from "react-toastify";
import { SITE_URL } from "../config";
import { supabase } from "../supabase/client";

export async function getServerSideProps() {
  const res = await axios.get(`${SITE_URL}/api/hello`, { withCredentials: true });
  return { props: {} };
}

export default function Home() {
  const signoutHandler = async () => {
    const { error } = await supabase.auth.signOut();
    let result = "Logout succcess";
    if (error) result = "Logout unccessful";
    toast.error(result, {
      position: "top-left",
      autoClose: 2000,
      hideProgressBar: false,
      closeOnClick: true,
      pauseOnHover: true,
      draggable: true,
      progress: undefined,
      theme: "light",
    });
  };

  return (
    <>
      <Head>
        <title>Dex</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <h1>HOME </h1>
        <h2 onClick={signoutHandler}>Signout </h2>
      </main>
    </>
  );
}
